<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenHand</AssemblyName>
    <RootNamespace>OpenHand</RootNamespace>
    <Version>0.2.2</Version>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VintageStoryPath)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(VintageStoryPath)/Lib/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="cairo-sharp">
      <HintPath>$(VintageStoryPath)/Lib/cairo-sharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(VintageStoryPath)/Lib/protobuf-net.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="modinfo.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
